### PR TITLE
Replace dns seed ppcoin.net with primecoin.info

### PR DESCRIPTION
**Pull request by sunnyking**
New dns seed at seed.primecoin.info.
ppcoin.net dns service will be decommissioned.

### CODE REVIEW

**Comment by eXtremal-ik7** [comment]
**Summary:**

> seed.primecoin.info
> 220.241.124.252   user agent: /Satoshi:0.16.1/Primecoin:0.1.6.1/                                  ???
> 13.52.96.166      user agent: /Satoshi:0.16.0/Primecoin:0.1.5/                                    ???
> 89.179.119.195    user agent: /Satoshi:0.8.6/Primecoin:0.1.3-intermediary/                        eXtremal
> 89.21.149.15      user agent: /Satoshi:0.16.0/Primecoin:0.1.5/                                    eXtremal
> 51.38.36.126      user agent: /Satoshi:0.8.6/Primecoin:0.1.3-intermediary/                        eXtremal
> 
> seed.primecoin.org
> 220.229.225.80    offline
> 3.0.77.125        offline
> 47.244.8.248      user agent: /Satoshi:0.8.7/Primecoin:0.1.2(v0.1.2.0-unk-beta)/                  ???
> 47.75.214.199     offline
> 122.55.217.152    offline
> 47.52.209.188     offline
> 47.88.158.250     offline
> 
> primeseed.muuttuja.org
> 37.187.75.24      user agent: /Satoshi:0.8.6/Primecoin:0.1.2(v0.1.2xpm-hp14-6-g21093429-beta)/;   muuttuja
> 
> xpm.dnsseed.coinsforall.io
> 37.187.50.246     user agent: /Satoshi:0.8.6/Primecoin:0.1.3-intermediary/;                       eXtremal (xpmforall.org)
> 51.38.36.126      user agent: /Satoshi:0.8.6/Primecoin:0.1.3-intermediary/                        eXtremal
> 151.80.96.105     user agent: /Satoshi:0.8.6/Primecoin:0.1.3-intermediary/;                       eXtremal (coinsforall.io)
> 89.21.149.15      user agent: /Satoshi:0.16.0/Primecoin:0.1.5/                                    eXtremal
> 89.179.119.195    user agent: /Satoshi:0.8.6/Primecoin:0.1.3-intermediary/                        eXtremal

**seed.primecoin.info includes 3 my nodes, 89.21.149.15 is running 24/7 desktop, but can be changed in this month.
seed.primecoin.org contains 6 offline addresses**

If it's ok I'll approve pull request.
Also, I'll make dns seed for testnet, have 2 nodes.

**Comment by eXtremal-ik7** [comment]
About testnet:

> tnseed.primecoin.info
> ** server can't find tnseed.primecoin.info: NXDOMAIN
> 
> primeseedtn.muuttuja.org
> 37.187.75.24      user agent: /Satoshi:0.8.6/Primecoin:0.1.2(v0.1.2xpm-hp14-6-g21093429-beta)/    muuttuja
> 
> tnseed.primecoin.org
> *** Can't find tnseed.primecoin.org: No answer

**Comment by eXtremal-ik7** [comment]
Valid dns seed for testnet:
**xpmtestnet.dnsseed.coinsforall.io**

primeseedtn.muuttuja.org also still alive

**Comment by sunnyking** [comment]
Added your testnet dnsseed. Enabled tnseed.primecoin.org, this node shares with a mainnet node.
tnseed.primecoin.info though will need to be set up in a later date.

**Comment by sunnyking** [comment]
Renamed testnet dnsseed to seed.testnet.primecoin.org, operating as of today;
Renamed testnet dnsseed to testseed.primecoin.info, to be operational within a week.

**Pull request merged**
